# -*- coding: utf-8 -*-
"""StudentScorePredict.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h6B1IA2oJQpL2F_m4iwUgmbdmIegUvj5
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
data = {
'Student_ID': range(1, 101),
'Study_Hours': np.random.uniform(1, 10, 100),
'Attendance': np.random.uniform(50, 100, 100),
'Previous_Marks': np.random.uniform(40, 95, 100),
'Internal_Marks': np.random.uniform(10, 30, 100),
'Final_Result': np.random.choice(['Pass', 'Fail'], 100)
}
df = pd.DataFrame(data)
df.head()

df.isnull().sum()

df.info()

le = LabelEncoder()
df['Final_Result'] = le.fit_transform(df['Final_Result'])
df

df['Final_Result'].value_counts()

plt.figure(figsize=(8, 5))
sns.regplot(x='Study_Hours', y='Previous_Marks', data=df)
plt.title('Study Hours vs Previous Marks')
plt.show()

plt.figure(figsize=(8, 5))
sns.violinplot(x='Final_Result', y='Attendance', data=df)
plt.title('Attendance Distribution by Result')
plt.show()

plt.figure(figsize=(10, 6))
sns.heatmap(df.corr(), annot=True, cmap='coolwarm')
plt.title('Feature Correlation Heatmap')
plt.show()

X = df.drop(['Student_ID', 'Final_Result'], axis=1)
y = df['Final_Result']

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(),
    "Naive Bayes": GaussianNB(),
    "SVM": SVC()
}
results = {}

print(" Model Performance ")
for name, model in models.items():
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    results[name] = accuracy_score(y_test, y_pred)
    print(f"\n{name}:\n{classification_report(y_test, y_pred)}")

new=(5,1.551328,62.596255,63.459231,22.930568)
new=(1.551328,62.596255,63.459231,22.930568)
n=np.asarray(new)
n_reshape=n.reshape(1,-1)
prediction=model.predict(n_reshape)
n_scaled = scaler.transform(n_reshape)
prediction=model.predict(n_scaled)
prediction

plt.figure(figsize=(8, 4))
plt.bar(results.keys(), results.values(), color='skyblue')
plt.title("Model Accuracy Comparison")
plt.ylabel("Accuracy")
plt.show()

final_model = DecisionTreeClassifier().fit(X_train, y_train)
df['Predicted_Result'] = final_model.predict(scaler.transform(df[X.columns]))
at_risk_students = df[df['Predicted_Result'] == 0]

print("\n--- At-Risk Students List ---")
print(at_risk_students[['Student_ID', 'Predicted_Result']])